# Generated by Django 3.1.3 on 2020-11-11 10:30

import distributions_list.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short_info', models.CharField(max_length=250, verbose_name='Кратко')),
                ('full_info', models.TextField(verbose_name='Информация')),
                ('icon', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('popularity', distributions_list.models.IntegerRangeField(verbose_name='Популярность')),
                ('society_support', distributions_list.models.IntegerRangeField(verbose_name='Поддерживаемость сообществом')),
                ('stability', distributions_list.models.IntegerRangeField(verbose_name='Надёжность и стабильность')),
                ('user_friendly', distributions_list.models.IntegerRangeField(verbose_name='Простота в использовании')),
                ('programs_update_frequency', distributions_list.models.IntegerRangeField(verbose_name='Частота обновлений программ')),
                ('customizability', distributions_list.models.IntegerRangeField(verbose_name='Настраиваемость')),
                ('consumption', distributions_list.models.IntegerRangeField(verbose_name='Потребление')),
            ],
            options={
                'verbose_name': 'Дистрибутив',
                'verbose_name_plural': 'Дистрибутивы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('dist_id', models.IntegerField(verbose_name='ID дистрибутива')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rate', models.IntegerField(verbose_name='Оценка')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
