# Generated by Django 3.1.3 on 2020-11-11 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions_list', '0002_auto_20201111_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='dist_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reviews',
            name='ID дистрибутива',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='distributions_list.distributions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='ID пользователя',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
