# Generated by Django 3.1.3 on 2020-11-11 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions_list', '0003_auto_20201111_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ID дистрибутива',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='ID пользователя',
        ),
        migrations.AddField(
            model_name='reviews',
            name='dist_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='distributions_list.distributions', verbose_name='ID дистрибутива'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='ID пользователя'),
            preserve_default=False,
        ),
    ]
