# Generated by Django 3.1.3 on 2020-11-11 16:42

import distributions_list.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions_list', '0004_auto_20201111_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=distributions_list.models.IntegerRangeField(verbose_name='Оценка'),
        ),
    ]
