# Generated by Django 3.1.3 on 2020-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions_list', '0005_auto_20201111_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributions',
            name='icon',
            field=models.ImageField(upload_to='distributions_list/static/distributions_list/img/distributions_logos/', verbose_name='Изображение'),
        ),
    ]
