# Generated by Django 3.1.3 on 2020-11-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions_list', '0009_auto_20201115_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributions',
            name='icon_path',
            field=models.CharField(default='distributions_list/img/tux-seeklogo.com.svg', max_length=250, verbose_name='Путь к изображению'),
        ),
    ]
